services:
  rtcw-server:
    image: ghcr.io/ekrunch/iortcw-server-docker:latest
    container_name: rtcw-server
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      # User ID / Group ID to run the server as. These can be whatever you'd like.
      # Note that files will be chown'd by the startup scripts.
      - PUID=27960
      - PGID=27960
      # This is too high for a normal server, but ensures you won't run out of memory in a big map.
      - SV_HUNKMEGS=128
      # Disable Anti-Cheat - Usually only used for a private server with friends.
      # Friends that don't cheat, that is...
      - SV_PUNKBUSTER=0
      # Server port - Make sure to adjust the "ports" section to match the port set here.
      # If you're using firewalls, make sure to open this port for both TCP and UDP, as the server
      # uses both protocols.
      - SV_NETPORT=27960
      # Do not include a path here. Server configurations should be located in "<home volume>/server.iortcw/main"
      - SV_SERVERCONFIGFILE=server.cfg
    ports:
      - "27960:27960/udp"
      - "27960:27960/tcp"
    volumes:
      # Path to the official RtCW data files. They should be in a subfolder called "main". All that is needed is the *.pk3 files from the official RtCW distribution
      - /mnt/rtcw/gamefiles:/var/cache/rtcw-server/gamefiles
      # This will become the home directory for the iortcw user. The server.cfg and additional configuration files get placed here.
      - /mnt/rtcw/home:/var/cache/rtcw-server/home
    networks:
      - frontend

networks:
  frontend:
    external: true
