services:
  rtcw-server:
    build:
      context: build
      dockerfile: Containerfile
    image: ekrunch/uxwh-custom-rtcw-server:latest
    container_name: rtcw-server
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      # User ID / Group ID to run the server as.
      # Note that files will be chown'd by the startup scripts.
      - PUID=2796
      - PGID=2796
      # This is far too high for a server, but ensures you won't run out of memory in a big map.
      - SV_HUNKMEGS=128
      - SV_PUNKBUSTER=0
      # Make sure to adjust the "ports" section to match the port set here.
      - SV_NETPORT=27960
      # Do not include a path here.
      - SV_SERVERCONFIGFILE=server.cfg
    ports:
      - "27960:27960/udp"
      - "27960:27960/tcp"
    volumes:
      # Path to the official RtCW data files. They should be in a subfolder called "main". All that is needed is the *.pk3 files from the official RtCW distribution
      - /mnt/rtcw/gamefiles:/var/cache/rtcw-server/gamefiles
      # This will become the home directory for the iortcw user. The server.cfg and additional configuration files get placed here.
      - /mnt/rtcw/home:/var/cache/rtcw-server/home
    networks:
      - frontend

networks:
  frontend:
    external: true
